import re

VULN_PATTERNS = {
    "SQL Error": re.compile(r"(sql\s*exception|sql\s*syntax|warning.*mysql.*|unclosed\s*quotation\s*mark|microsoft\s*ole\s*db\s*provider|odbc\s*sql\s*server\s*driver|pg_query\()", re.IGNORECASE|re.DOTALL),
    "SQL Injection": re.compile(r"(\bunion\s+select\s|\bselect\s+\*\s+from\s|\bsleep\(|\b'or\s+1=1\b|\b'or\s+'a'='a\b|--|#|xp_cmdshell|information_schema)", re.IGNORECASE|re.DOTALL),
    "XSS": re.compile("|".join([
        r"<\s*script[^>]*?>.*?<\s*/\s*script\s*>",
        r"<\s*img[^>]+onerror\s*=.*?>",
        r"<\s*svg[^>]*on(load|error)\s*=",
        r"<\s*iframe\b.*?>",
        r"<\s*body\b[^>]*onload\s*=",
        r"javascript\s*:",
        r"<\s*\w+\s+on\w+\s*=",
        r"<\s*s\s*c\s*r\s*i\s*p\s*t[^>]*>",
        r"&#x3c;\s*script\s*&#x3e;",
        r"<scr(?:.*?)ipt>",
        r"</scr(?:.*?)ipt>",
        r"<\s*script[^>]*src\s*=.*?>",
        r"expression\s*\(",
        r"vbscript\s*:",
        r"mozbinding\s*:",
        r"javascript:alert\(document.domain\)",
        r"<script src=['\"]http://[^>]*?>"
    ]), re.IGNORECASE|re.DOTALL),
    "Directory Listing": re.compile(r"(<title>\s*index of\s*/\s*</title>|directory\s+listing\s+for)", re.IGNORECASE|re.DOTALL),
    "File Inclusion": re.compile(r"(include|require)(_once)?\s*\(.*?http://", re.IGNORECASE|re.DOTALL),
    "Server Error": re.compile(r"(internal\s+server\s+error|500\s+internal|traceback\s*\(most\s+recent\s+call\s+last\))", re.IGNORECASE|re.DOTALL),
    "Shellshock": re.compile(r"\(\)\s*\{:\;};", re.IGNORECASE|re.DOTALL),
    "Remote Code Execution": re.compile(r"(exec\(|system\(|shell_exec\(|/bin/sh|eval\(|\bpython\s+-c\s)", re.IGNORECASE|re.DOTALL),
    "LFI/RFI": re.compile(r"(etc/passwd|boot.ini|\\\\\\\\\.\\\\pipe\\\\|\\\.\\pipe\\)", re.IGNORECASE|re.DOTALL),
    "SSRF": re.compile(r"(127\.0\.0\.1|localhost|metadata\.google\.internal)", re.IGNORECASE|re.DOTALL),
    "Path Traversal": re.compile(r"(\.\./\.\./|\.\./|\.\.\\)", re.IGNORECASE|re.DOTALL),
    "Command Injection": re.compile(r"(\|\||&&|;|/bin/bash|/bin/zsh)", re.IGNORECASE|re.DOTALL),
    "WordPress Leak": re.compile(r"(wp-content|wp-includes|wp-admin)", re.IGNORECASE|re.DOTALL),
    "Java Error": re.compile(r"(java\.lang\.|exception\s+in\s+thread\s+\"main\")", re.IGNORECASE|re.DOTALL),
    "Open Redirect": re.compile(r"(=\s*https?:\/\/)", re.IGNORECASE|re.DOTALL),
    "Deserialization": re.compile(r"(java\.io\.objectinputstream|ysoserial|__proto__|constructor\.prototype)", re.IGNORECASE|re.DOTALL),
    "XXE": re.compile(r"(<!doctype\s+[^>]*\[.*<!entity\s+[^>]*system)", re.IGNORECASE|re.DOTALL),
    "File Upload": re.compile(r"(multipart/form-data.*filename=)", re.IGNORECASE|re.DOTALL),
    "Prototype Pollution": re.compile(r"(\.__proto__|object\.prototype|object\.setprototypeof)", re.IGNORECASE|re.DOTALL),
    "NoSQL Injection": re.compile(r"(db\.\w+\.find\(|\$\w+\{|{\s*\$where\s*:)", re.IGNORECASE|re.DOTALL),
    "Exposed Git Directory": re.compile(r"(\.git/HEAD|\.gitignore|\.git/config)", re.IGNORECASE|re.DOTALL),
    "Potential Secrets": re.compile(r"(aws_access_key_id|aws_secret_access_key|api_key|private_key|authorization:\s*bearer\s+[0-9a-z\-_\.]+)", re.IGNORECASE|re.DOTALL),
    "JWT Token Leak": re.compile(r"(eyjh[a-z0-9_-]*\.[a-z0-9_-]+\.[a-z0-9_-]+)", re.IGNORECASE|re.DOTALL),
    "ETC Shadow Leak": re.compile(r"/etc/shadow", re.IGNORECASE|re.DOTALL),
    "Possible Password Leak": re.compile(r"(password\s*=\s*\w+)", re.IGNORECASE|re.DOTALL),
    "CC Leak": re.compile(r"\b(?:\d[ -]*?){13,16}\b"),
    "CRLF Injection": re.compile(r"(\r\n|%0d%0a|%0A%0D)", re.IGNORECASE|re.DOTALL),
    "HTTP Request Smuggling": re.compile(r"(content-length:\s*\d+.*\r?\n\s*transfer-encoding:\s*chunked|transfer-encoding:\s*chunked.*\r?\n\s*content-length:\s*\d+)", re.IGNORECASE|re.DOTALL),
    "LDAP Injection": re.compile(r"(\(\w+=\*\)|\|\(\w+=\*\)|\(\w+~=\*)", re.IGNORECASE|re.DOTALL),
    "XPath Injection": re.compile(r"(/[^/]+/|\[[^\]]+\]|text\(\)=)", re.IGNORECASE|re.DOTALL),
    "Exposed S3 Bucket": re.compile(r"s3\.amazonaws\.com", re.IGNORECASE),
    "Exposed Azure Blob": re.compile(r"blob\.core\.windows\.net", re.IGNORECASE),
    "Exposed K8s Secrets": re.compile(r"kube[\s_-]*config|k8s[\s_-]*secret|kubeadm[\s_-]*token", re.IGNORECASE|re.DOTALL),
    "npm Token": re.compile(r"npm[_-]token_[a-z0-9]{36}", re.IGNORECASE|re.DOTALL)
}

HEADER_PATTERNS = {
    "Missing Security Headers": ["Content-Security-Policy","X-Content-Type-Options","X-Frame-Options","X-XSS-Protection","Strict-Transport-Security"],
    "Outdated or Insecure Server": re.compile(r"(apache/2\.2\.\d|nginx/1\.10\.\d|iis/6\.0|php/5\.2)", re.IGNORECASE),
}

VULN_EXPLANATIONS = {
    "SQL Error":"Server returned DB error messages.","SQL Injection":"Likely injection in SQL queries.","XSS":"Injected scripts.",
    "Directory Listing":"Exposed directory contents.","File Inclusion":"Local/remote file inclusion.","Server Error":"HTTP 500 or similar.",
    "Shellshock":"Bash vulnerability.","Remote Code Execution":"User input runs code.","LFI/RFI":"File references for inclusion.",
    "SSRF":"Server-Side Request Forgery.","Path Traversal":"Directory traversal.","Command Injection":"Shell commands injected.",
    "WordPress Leak":"WordPress paths/files.","Java Error":"Java exceptions or traces.","Open Redirect":"Redirect to external URL.",
    "Deserialization":"Unsafe object deserialization.","XXE":"XML External Entity usage.","File Upload":"Multipart form can upload.",
    "Prototype Pollution":"JS prototype manipulation.","NoSQL Injection":"NoSQL references.","Exposed Git Directory":"Git config visible.",
    "Potential Secrets":"API keys or tokens leaked.","JWT Token Leak":"JWT tokens exposed.","ETC Shadow Leak":"/etc/shadow reference.",
    "Missing Security Headers":"Key headers absent.","Outdated or Insecure Server":"Old server.",
    "Cookies lack 'Secure'/'HttpOnly'":"Cookie flags missing.","Suspicious param name:":"Param name looks malicious.",
    "Suspicious param value in":"Param value looks malicious.","Form uses GET with password/hidden":"Sensitive data in GET.",
    "Suspicious form fields (cmd/shell/token)":"Malicious field names.","POST form without CSRF token":"Form missing CSRF token.",
    "Service Disruption":"5xx errors or repeated failures.","Possible Password Leak":"Possible credential leakage.","CC Leak":"Credit card pattern.",
    "CRLF Injection":"CRLF discovered.","HTTP Request Smuggling":"Conflicting request headers.","LDAP Injection":"Directory service injection.",
    "XPath Injection":"XPath queries injected.","Exposed S3 Bucket":"Possible public S3.","Exposed Azure Blob":"Unsecured Azure blob.",
    "Exposed K8s Secrets":"Possible K8s secrets.","npm Token":"npm token possibly leaked.","ChromeDriver Error":"Selenium error.",
    "No explanation":"No explanation"
}
